# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Thalisson Vinicius\Documents\Programacao\python\kwai-bot\ui\edit-profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class EditProfileGUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(380, 219)
        MainWindow.setStyleSheet('background-color: rgb(50, 50, 62);')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet('background-color: rgb(50, 50, 62);')
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName('main_frame')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.label_25 = QtWidgets.QLabel(self.main_frame)
        self.label_25.setStyleSheet(
            'font: 14pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName('label_25')
        self.verticalLayout_2.addWidget(self.label_25)
        self.lineedit_username = QtWidgets.QLineEdit(self.main_frame)
        self.lineedit_username.setMinimumSize(QtCore.QSize(300, 30))
        self.lineedit_username.setStyleSheet(
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'padding-left: 5px;\n'
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);'
        )
        self.lineedit_username.setObjectName('lineedit_username')
        self.verticalLayout_2.addWidget(self.lineedit_username)
        self.lineedit_password = QtWidgets.QLineEdit(self.main_frame)
        self.lineedit_password.setMinimumSize(QtCore.QSize(300, 30))
        self.lineedit_password.setStyleSheet(
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'padding-left: 5px;\n'
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);'
        )
        self.lineedit_password.setObjectName('lineedit_password')
        self.verticalLayout_2.addWidget(self.lineedit_password)
        self.combobox_gender = QtWidgets.QComboBox(self.main_frame)
        self.combobox_gender.setMinimumSize(QtCore.QSize(300, 30))
        self.combobox_gender.setStyleSheet(
            'QComboBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(172, 172, 174);\n'
            'border-top-left-radius: 5px;\n'
            'border-bottom-left-radius: 5px;\n'
            'font: 75 11px "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'padding-right: 7px;\n'
            '}\n'
            '\n'
            'QComboBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '}\n'
            '\n'
            'QComboBox::drop-down {\n'
            '    background-color: rgb(39, 39, 47);\n'
            '    width: 25px; \n'
            '    border-right: 0px;\n'
            '}\n'
            '\n'
            'QComboBox::down-arrow {\n'
            '    image: url(:/imagens/imagens/dropdown.png);\n'
            '}\n'
            '\n'
            ''
        )
        self.combobox_gender.setObjectName('combobox_gender')
        self.combobox_gender.addItem('')
        self.combobox_gender.addItem('')
        self.verticalLayout_2.addWidget(self.combobox_gender)
        self.button_save = QtWidgets.QPushButton(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_save.sizePolicy().hasHeightForWidth()
        )
        self.button_save.setSizePolicy(sizePolicy)
        self.button_save.setMinimumSize(QtCore.QSize(150, 35))
        self.button_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_save.setStyleSheet(
            'QPushButton{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: center;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_save.setObjectName('button_save')
        self.verticalLayout_2.addWidget(self.button_save)
        self.verticalLayout.addWidget(
            self.main_frame, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter
        )
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'MainWindow'))
        self.label_25.setText(_translate('MainWindow', 'Editar perfil'))
        self.lineedit_username.setPlaceholderText(
            _translate('MainWindow', 'Insira o usuário')
        )
        self.lineedit_password.setPlaceholderText(
            _translate('MainWindow', 'Insira a senha')
        )
        self.combobox_gender.setItemText(
            0, _translate('MainWindow', 'Masculino')
        )
        self.combobox_gender.setItemText(
            1, _translate('MainWindow', 'Feminino')
        )
        self.button_save.setText(_translate('MainWindow', 'Salvar'))
