# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Thalisson Vinicius\Documents\Programacao\python\kwai-bot\ui\view-group.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class GroupGUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(653, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet('background-color: rgb(50, 50, 62);')
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName('main_frame')
        self.button_start_all = QtWidgets.QPushButton(self.main_frame)
        self.button_start_all.setGeometry(QtCore.QRect(100, 400, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_start_all.sizePolicy().hasHeightForWidth()
        )
        self.button_start_all.setSizePolicy(sizePolicy)
        self.button_start_all.setMinimumSize(QtCore.QSize(150, 35))
        self.button_start_all.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.button_start_all.setStyleSheet(
            'QPushButton{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: center;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_start_all.setObjectName('button_start_all')
        self.button_stop_all = QtWidgets.QPushButton(self.main_frame)
        self.button_stop_all.setGeometry(QtCore.QRect(260, 400, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_stop_all.sizePolicy().hasHeightForWidth()
        )
        self.button_stop_all.setSizePolicy(sizePolicy)
        self.button_stop_all.setMinimumSize(QtCore.QSize(150, 35))
        self.button_stop_all.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.button_stop_all.setStyleSheet(
            'QPushButton{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: center;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_stop_all.setObjectName('button_stop_all')
        self.button_edit_group = QtWidgets.QPushButton(self.main_frame)
        self.button_edit_group.setGeometry(QtCore.QRect(420, 400, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_edit_group.sizePolicy().hasHeightForWidth()
        )
        self.button_edit_group.setSizePolicy(sizePolicy)
        self.button_edit_group.setMinimumSize(QtCore.QSize(150, 35))
        self.button_edit_group.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.button_edit_group.setStyleSheet(
            'QPushButton{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: center;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_edit_group.setObjectName('button_edit_group')
        self.frame_added_accounts = QtWidgets.QFrame(self.main_frame)
        self.frame_added_accounts.setGeometry(QtCore.QRect(60, 90, 541, 300))
        self.frame_added_accounts.setMinimumSize(QtCore.QSize(541, 300))
        self.frame_added_accounts.setStyleSheet('')
        self.frame_added_accounts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_added_accounts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_added_accounts.setObjectName('frame_added_accounts')
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(
            self.frame_added_accounts
        )
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName('verticalLayout_23')
        self.frame_31 = QtWidgets.QFrame(self.frame_added_accounts)
        self.frame_31.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_31.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName('frame_31')
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName('horizontalLayout_12')
        self.label_26 = QtWidgets.QLabel(self.frame_31)
        self.label_26.setMinimumSize(QtCore.QSize(150, 0))
        self.label_26.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_26.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'border-right: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;\n'
            'border-top-left-radius:5px;'
        )
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName('label_26')
        self.horizontalLayout_12.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.frame_31)
        self.label_27.setMinimumSize(QtCore.QSize(236, 0))
        self.label_27.setMaximumSize(QtCore.QSize(236, 16777215))
        self.label_27.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'border-right: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;'
        )
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName('label_27')
        self.horizontalLayout_12.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.frame_31)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_28.setMaximumSize(QtCore.QSize(173, 16777215))
        self.label_28.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;\n'
            'border-top-right-radius:5px;'
        )
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName('label_28')
        self.horizontalLayout_12.addWidget(self.label_28)
        self.verticalLayout_23.addWidget(self.frame_31)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_added_accounts)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 220))
        self.scrollArea_2.setStyleSheet('border: 0px;')
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName('scrollArea_2')
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(
            QtCore.QRect(0, 0, 541, 270)
        )
        self.scrollAreaWidgetContents_2.setObjectName(
            'scrollAreaWidgetContents_2'
        )
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents_2
        )
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName('verticalLayout_25')
        self.frame_32 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName('frame_32')
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName('verticalLayout_26')
        self.frame_33 = QtWidgets.QFrame(self.frame_32)
        self.frame_33.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_33.setStyleSheet('')
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName('frame_33')
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName('horizontalLayout_16')
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_34.setStyleSheet('')
        self.frame_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName('frame_34')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label = QtWidgets.QLabel(self.frame_34)
        self.label.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label.setObjectName('label')
        self.horizontalLayout.addWidget(self.label)
        self.label_29 = QtWidgets.QLabel(self.frame_34)
        self.label_29.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName('label_29')
        self.horizontalLayout.addWidget(self.label_29)
        self.horizontalLayout_16.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_33)
        self.frame_35.setMinimumSize(QtCore.QSize(236, 0))
        self.frame_35.setMaximumSize(QtCore.QSize(236, 16777215))
        self.frame_35.setStyleSheet('')
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName('frame_35')
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_32.setObjectName('verticalLayout_32')
        self.label_31 = QtWidgets.QLabel(self.frame_35)
        self.label_31.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName('label_31')
        self.verticalLayout_32.addWidget(self.label_31)
        self.horizontalLayout_16.addWidget(self.frame_35)
        self.frame_37 = QtWidgets.QFrame(self.frame_33)
        self.frame_37.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_37.setStyleSheet('border: 0px;')
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName('frame_37')
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName('verticalLayout_29')
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_37)
        self.pushButton_8.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_8.setMaximumSize(QtCore.QSize(18, 16777215))
        self.pushButton_8.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.pushButton_8.setStyleSheet(
            'background-image: url(:/imagens/imagens/more_resized.png);'
        )
        self.pushButton_8.setText('')
        self.pushButton_8.setObjectName('pushButton_8')
        self.verticalLayout_29.addWidget(self.pushButton_8)
        self.horizontalLayout_16.addWidget(
            self.frame_37, 0, QtCore.Qt.AlignHCenter
        )
        self.verticalLayout_26.addWidget(self.frame_33)
        self.verticalLayout_25.addWidget(self.frame_32, 0, QtCore.Qt.AlignTop)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_23.addWidget(self.scrollArea_2)
        self.label_current_log = QtWidgets.QLabel(self.main_frame)
        self.label_current_log.setGeometry(QtCore.QRect(40, 50, 561, 22))
        self.label_current_log.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_current_log.setAlignment(QtCore.Qt.AlignCenter)
        self.label_current_log.setObjectName('label_current_log')
        self.label_25 = QtWidgets.QLabel(self.main_frame)
        self.label_25.setGeometry(QtCore.QRect(120, 10, 401, 41))
        self.label_25.setStyleSheet(
            'font: 15pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName('label_25')
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'MainWindow'))
        self.button_start_all.setText(
            _translate('MainWindow', 'Iniciar grupo')
        )
        self.button_stop_all.setText(_translate('MainWindow', 'Parar grupo'))
        self.button_edit_group.setText(
            _translate('MainWindow', 'Editar grupo')
        )
        self.label_26.setText(_translate('MainWindow', 'Usuário'))
        self.label_27.setText(_translate('MainWindow', 'Ações realizadas'))
        self.label_28.setText(_translate('MainWindow', 'Outros'))
        self.label.setText(_translate('MainWindow', '=>'))
        self.label_29.setText(_translate('MainWindow', '@willenrocha'))
        self.label_31.setText(
            _translate('MainWindow', '0           0           0')
        )
        self.label_current_log.setText(
            _translate(
                'MainWindow', '[00:04] Realizando login em @willenrocha'
            )
        )
        self.label_25.setText(_translate('MainWindow', 'Grupo: android'))


from src.gui.resources import imagens_rc
