# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Thalisson Vinicius\Documents\Programacao\python\kwai-bot\ui\kwai_bot.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from src.gui.resources import imagens_rc


class IGBotGUI(object):
    def setupUi(self, kwai_bot):
        kwai_bot.setObjectName('kwai_bot')
        kwai_bot.resize(772, 453)
        self.centralwidget = QtWidgets.QWidget(kwai_bot)
        self.centralwidget.setObjectName('centralwidget')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName('verticalLayout')
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName('main_frame')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.lateral_menu = QtWidgets.QFrame(self.main_frame)
        self.lateral_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.lateral_menu.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lateral_menu.setStyleSheet('background-color: rgb(39, 39, 47);')
        self.lateral_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lateral_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lateral_menu.setObjectName('lateral_menu')
        self.frame_button_devices = QtWidgets.QFrame(self.lateral_menu)
        self.frame_button_devices.setGeometry(QtCore.QRect(0, 20, 151, 31))
        self.frame_button_devices.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_devices.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_devices.setObjectName('frame_button_devices')
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.frame_button_devices
        )
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName('verticalLayout_2')
        self.page_devices = QtWidgets.QPushButton(self.frame_button_devices)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.page_devices.sizePolicy().hasHeightForWidth()
        )
        self.page_devices.setSizePolicy(sizePolicy)
        self.page_devices.setMinimumSize(QtCore.QSize(131, 31))
        self.page_devices.setStyleSheet(
            'QPushButton{\n'
            'font: 12px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;\n'
            'background-image: url(:/imagens/imagens/cell-phone_resized.png);\n'
            'background-position: left;\n'
            'background-repeat: none;\n'
            'border: 0px;\n'
            'background-origin: content;\n'
            'padding-left: 14px;\n'
            '}\n'
            'QPushButton:hover{\n'
            'background-color: rgb(69, 69, 77);\n'
            '}\n'
            ''
        )
        self.page_devices.setObjectName('page_devices')
        self.verticalLayout_2.addWidget(self.page_devices)
        self.frame_button_start = QtWidgets.QFrame(self.lateral_menu)
        self.frame_button_start.setGeometry(QtCore.QRect(0, 60, 151, 31))
        self.frame_button_start.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_start.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_start.setObjectName('frame_button_start')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_button_start)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.page_start = QtWidgets.QPushButton(self.frame_button_start)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.page_start.sizePolicy().hasHeightForWidth()
        )
        self.page_start.setSizePolicy(sizePolicy)
        self.page_start.setMinimumSize(QtCore.QSize(131, 31))
        self.page_start.setStyleSheet(
            'QPushButton{\n'
            'font: 12px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;\n'
            'background-image: url(:/imagens/imagens/play-button_resized.png);\n'
            'background-position: left;\n'
            'background-repeat: none;\n'
            'border: 0px;\n'
            'background-origin: content;\n'
            'padding-left: 14px;\n'
            'text-align: left;\n'
            '}\n'
            'QPushButton:hover{\n'
            'background-color: rgb(69, 69, 77);\n'
            '}\n'
            ''
        )
        self.page_start.setObjectName('page_start')
        self.verticalLayout_3.addWidget(self.page_start)
        self.frame_button_config = QtWidgets.QFrame(self.lateral_menu)
        self.frame_button_config.setGeometry(QtCore.QRect(0, 100, 151, 31))
        self.frame_button_config.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_config.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_config.setObjectName('frame_button_config')
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_button_config)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName('verticalLayout_4')
        self.page_options = QtWidgets.QPushButton(self.frame_button_config)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.page_options.sizePolicy().hasHeightForWidth()
        )
        self.page_options.setSizePolicy(sizePolicy)
        self.page_options.setMinimumSize(QtCore.QSize(131, 31))
        self.page_options.setStyleSheet(
            'QPushButton{\n'
            'font: 12px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;\n'
            'background-image: url(:/imagens/imagens/gear_resized.png);\n'
            'background-position: left;\n'
            'background-repeat: none;\n'
            'border: 0px;\n'
            'background-origin: content;\n'
            'padding-left: 14px;\n'
            'text-align: center;\n'
            '}\n'
            'QPushButton:hover{\n'
            'background-color: rgb(69, 69, 77);\n'
            '}\n'
            ''
        )
        self.page_options.setObjectName('page_options')
        self.verticalLayout_4.addWidget(self.page_options)
        self.frame_30 = QtWidgets.QFrame(self.lateral_menu)
        self.frame_30.setGeometry(QtCore.QRect(0, 137, 151, 41))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName('frame_30')
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName('verticalLayout_24')
        self.horizontalLayout.addWidget(self.lateral_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_frame)
        self.stackedWidget.setObjectName('stackedWidget')
        self.widget_page_config = QtWidgets.QWidget()
        self.widget_page_config.setObjectName('widget_page_config')
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_page_config)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName('verticalLayout_17')
        self.frame_14 = QtWidgets.QFrame(self.widget_page_config)
        self.frame_14.setStyleSheet('background-color: rgb(50, 50, 62);')
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName('frame_14')
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName('verticalLayout_18')
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName('frame_15')
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.frame_19 = QtWidgets.QFrame(self.frame_15)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName('frame_19')
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_20.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_20.setObjectName('verticalLayout_20')
        self.label_9 = QtWidgets.QLabel(self.frame_19)
        self.label_9.setMinimumSize(QtCore.QSize(0, 13))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_9.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName('label_9')
        self.verticalLayout_20.addWidget(self.label_9)
        self.frame_25 = QtWidgets.QFrame(self.frame_19)
        self.frame_25.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_25.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName('frame_25')
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_7.setObjectName('horizontalLayout_7')
        self.label_10 = QtWidgets.QLabel(self.frame_25)
        self.label_10.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName('label_10')
        self.horizontalLayout_7.addWidget(self.label_10)
        self.spinbox_min_time_actions = QtWidgets.QSpinBox(self.frame_25)
        self.spinbox_min_time_actions.setStyleSheet(
            'QSpinBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            '\n'
            'font: 75 8pt "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'background-position: right;\n'
            'background-repeat: none;\n'
            'background-origin: content;\n'
            'padding-right: 7px;\n'
            '    color: rgb(172, 172, 174);\n'
            '}\n'
            '\n'
            'QSpinBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '\n'
            '}\n'
            '\n'
            ''
        )
        self.spinbox_min_time_actions.setMaximum(9999)
        self.spinbox_min_time_actions.setObjectName('spinbox_min_time_actions')
        self.horizontalLayout_7.addWidget(self.spinbox_min_time_actions)
        self.label_11 = QtWidgets.QLabel(self.frame_25)
        self.label_11.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName('label_11')
        self.horizontalLayout_7.addWidget(self.label_11)
        self.spinbox_max_time_actions = QtWidgets.QSpinBox(self.frame_25)
        self.spinbox_max_time_actions.setStyleSheet(
            'QSpinBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            '\n'
            'font: 75 8pt "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'background-position: right;\n'
            'background-repeat: none;\n'
            'background-origin: content;\n'
            'padding-right: 7px;\n'
            '    color: rgb(172, 172, 174);\n'
            '}\n'
            '\n'
            'QSpinBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '\n'
            '}\n'
            '\n'
            ''
        )
        self.spinbox_max_time_actions.setMaximum(9999)
        self.spinbox_max_time_actions.setObjectName('spinbox_max_time_actions')
        self.horizontalLayout_7.addWidget(self.spinbox_max_time_actions)
        self.label_12 = QtWidgets.QLabel(self.frame_25)
        self.label_12.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName('label_12')
        self.horizontalLayout_7.addWidget(self.label_12)
        self.verticalLayout_20.addWidget(
            self.frame_25, 0, QtCore.Qt.AlignHCenter
        )
        self.label_13 = QtWidgets.QLabel(self.frame_19)
        self.label_13.setMinimumSize(QtCore.QSize(0, 13))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_13.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName('label_13')
        self.verticalLayout_20.addWidget(self.label_13)
        self.frame_27 = QtWidgets.QFrame(self.frame_19)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName('frame_27')
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_8.setObjectName('horizontalLayout_8')
        self.spinbox_actions_change_amount = QtWidgets.QSpinBox(self.frame_27)
        self.spinbox_actions_change_amount.setStyleSheet(
            'QSpinBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            '\n'
            'font: 75 11px "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'background-position: right;\n'
            'background-repeat: none;\n'
            'background-origin: content;\n'
            'padding-right: 7px;\n'
            '    color: rgb(172, 172, 174);\n'
            '}\n'
            '\n'
            'QSpinBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '\n'
            '}\n'
            '\n'
            ''
        )
        self.spinbox_actions_change_amount.setMaximum(9999)
        self.spinbox_actions_change_amount.setObjectName(
            'spinbox_actions_change_amount'
        )
        self.horizontalLayout_8.addWidget(self.spinbox_actions_change_amount)
        self.label_14 = QtWidgets.QLabel(self.frame_27)
        self.label_14.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName('label_14')
        self.horizontalLayout_8.addWidget(self.label_14)
        self.verticalLayout_20.addWidget(
            self.frame_27, 0, QtCore.Qt.AlignHCenter
        )
        self.label_15 = QtWidgets.QLabel(self.frame_19)
        self.label_15.setMinimumSize(QtCore.QSize(0, 13))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_15.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName('label_15')
        self.verticalLayout_20.addWidget(self.label_15)
        self.frame_21 = QtWidgets.QFrame(self.frame_19)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName('frame_21')
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(8)
        self.horizontalLayout_13.setObjectName('horizontalLayout_13')
        self.radiobutton_change_actions = QtWidgets.QRadioButton(self.frame_21)
        self.radiobutton_change_actions.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            '\n'
            '\n'
            ''
        )
        self.radiobutton_change_actions.setObjectName(
            'radiobutton_change_actions'
        )
        self.horizontalLayout_13.addWidget(self.radiobutton_change_actions)
        self.radiobutton_dont_change_actions = QtWidgets.QRadioButton(
            self.frame_21
        )
        self.radiobutton_dont_change_actions.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            ''
        )
        self.radiobutton_dont_change_actions.setObjectName(
            'radiobutton_dont_change_actions'
        )
        self.horizontalLayout_13.addWidget(
            self.radiobutton_dont_change_actions
        )
        self.verticalLayout_20.addWidget(
            self.frame_21, 0, QtCore.Qt.AlignHCenter
        )
        self.frame_change_actions = QtWidgets.QFrame(self.frame_19)
        self.frame_change_actions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_change_actions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_change_actions.setObjectName('frame_change_actions')
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(
            self.frame_change_actions
        )
        self.verticalLayout_19.setObjectName('verticalLayout_19')
        self.label_16 = QtWidgets.QLabel(self.frame_change_actions)
        self.label_16.setMinimumSize(QtCore.QSize(0, 13))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_16.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName('label_16')
        self.verticalLayout_19.addWidget(self.label_16)
        self.frame_22 = QtWidgets.QFrame(self.frame_change_actions)
        self.frame_22.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName('frame_22')
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_6.setObjectName('horizontalLayout_6')
        self.spinbox_seconds_to_change = QtWidgets.QSpinBox(self.frame_22)
        self.spinbox_seconds_to_change.setStyleSheet(
            'QSpinBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            '\n'
            'font: 75 11px "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'background-position: right;\n'
            'background-repeat: none;\n'
            'background-origin: content;\n'
            'padding-right: 7px;\n'
            '    color: rgb(172, 172, 174);\n'
            '}\n'
            '\n'
            'QSpinBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '\n'
            '}\n'
            '\n'
            ''
        )
        self.spinbox_seconds_to_change.setMaximum(9999)
        self.spinbox_seconds_to_change.setObjectName(
            'spinbox_seconds_to_change'
        )
        self.horizontalLayout_6.addWidget(self.spinbox_seconds_to_change)
        self.label_17 = QtWidgets.QLabel(self.frame_22)
        self.label_17.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName('label_17')
        self.horizontalLayout_6.addWidget(self.label_17)
        self.verticalLayout_19.addWidget(
            self.frame_22, 0, QtCore.Qt.AlignHCenter
        )
        self.verticalLayout_20.addWidget(self.frame_change_actions)
        self.label_18 = QtWidgets.QLabel(self.frame_19)
        self.label_18.setMinimumSize(QtCore.QSize(0, 13))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_18.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName('label_18')
        self.verticalLayout_20.addWidget(self.label_18)
        self.frame_23 = QtWidgets.QFrame(self.frame_19)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_23.setStyleSheet(
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'border: 0px;\n'
            'color: rgb(172, 172, 174);'
        )
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName('frame_23')
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName('horizontalLayout_15')
        self.checkbox_like = QtWidgets.QCheckBox(self.frame_23)
        self.checkbox_like.setObjectName('checkbox_like')
        self.horizontalLayout_15.addWidget(self.checkbox_like)
        self.checkbox_follow = QtWidgets.QCheckBox(self.frame_23)
        self.checkbox_follow.setObjectName('checkbox_follow')
        self.horizontalLayout_15.addWidget(self.checkbox_follow)
        self.verticalLayout_20.addWidget(
            self.frame_23, 0, QtCore.Qt.AlignHCenter
        )
        self.horizontalLayout_5.addWidget(
            self.frame_19, 0, QtCore.Qt.AlignVCenter
        )
        self.frame_20 = QtWidgets.QFrame(self.frame_15)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName('frame_20')
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_21.setObjectName('verticalLayout_21')
        self.label_19 = QtWidgets.QLabel(self.frame_20)
        self.label_19.setMinimumSize(QtCore.QSize(0, 13))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_19.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName('label_19')
        self.verticalLayout_21.addWidget(self.label_19)
        self.frame_24 = QtWidgets.QFrame(self.frame_20)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName('frame_24')
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(8)
        self.horizontalLayout_14.setObjectName('horizontalLayout_14')
        self.radiobutton_enable_goal = QtWidgets.QRadioButton(self.frame_24)
        self.radiobutton_enable_goal.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            '\n'
            '\n'
            ''
        )
        self.radiobutton_enable_goal.setObjectName('radiobutton_enable_goal')
        self.horizontalLayout_14.addWidget(self.radiobutton_enable_goal)
        self.radiobutton_disable_goal = QtWidgets.QRadioButton(self.frame_24)
        self.radiobutton_disable_goal.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            ''
        )
        self.radiobutton_disable_goal.setObjectName('radiobutton_disable_goal')
        self.horizontalLayout_14.addWidget(self.radiobutton_disable_goal)
        self.verticalLayout_21.addWidget(
            self.frame_24, 0, QtCore.Qt.AlignHCenter
        )
        self.frame_goal_actions = QtWidgets.QFrame(self.frame_20)
        self.frame_goal_actions.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_goal_actions.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_goal_actions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_goal_actions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_goal_actions.setObjectName('frame_goal_actions')
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(
            self.frame_goal_actions
        )
        self.horizontalLayout_9.setObjectName('horizontalLayout_9')
        self.spinbox_goal_actions = QtWidgets.QSpinBox(self.frame_goal_actions)
        self.spinbox_goal_actions.setStyleSheet(
            'QSpinBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            '\n'
            'font: 75 11px "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'background-position: right;\n'
            'background-repeat: none;\n'
            'background-origin: content;\n'
            'padding-right: 7px;\n'
            '    color: rgb(172, 172, 174);\n'
            '}\n'
            '\n'
            'QSpinBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '\n'
            '}\n'
            '\n'
            ''
        )
        self.spinbox_goal_actions.setMaximum(9999)
        self.spinbox_goal_actions.setObjectName('spinbox_goal_actions')
        self.horizontalLayout_9.addWidget(self.spinbox_goal_actions)
        self.label_21 = QtWidgets.QLabel(self.frame_goal_actions)
        self.label_21.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName('label_21')
        self.horizontalLayout_9.addWidget(self.label_21)
        self.verticalLayout_21.addWidget(
            self.frame_goal_actions, 0, QtCore.Qt.AlignHCenter
        )
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setMinimumSize(QtCore.QSize(0, 13))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_20.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName('label_20')
        self.verticalLayout_21.addWidget(self.label_20)
        self.frame_26 = QtWidgets.QFrame(self.frame_20)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName('frame_26')
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName('horizontalLayout_10')
        self.radiobutton_enable_rest_goal = QtWidgets.QRadioButton(
            self.frame_26
        )
        self.radiobutton_enable_rest_goal.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            '\n'
            '\n'
            ''
        )
        self.radiobutton_enable_rest_goal.setObjectName(
            'radiobutton_enable_rest_goal'
        )
        self.horizontalLayout_10.addWidget(self.radiobutton_enable_rest_goal)
        self.radiobutton_disable_rest_goal = QtWidgets.QRadioButton(
            self.frame_26
        )
        self.radiobutton_disable_rest_goal.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            ''
        )
        self.radiobutton_disable_rest_goal.setObjectName(
            'radiobutton_disable_rest_goal'
        )
        self.horizontalLayout_10.addWidget(self.radiobutton_disable_rest_goal)
        self.verticalLayout_21.addWidget(
            self.frame_26, 0, QtCore.Qt.AlignHCenter
        )
        self.frame_rest_goal = QtWidgets.QFrame(self.frame_20)
        self.frame_rest_goal.setMinimumSize(QtCore.QSize(0, 44))
        self.frame_rest_goal.setMaximumSize(QtCore.QSize(16777215, 44))
        self.frame_rest_goal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rest_goal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rest_goal.setObjectName('frame_rest_goal')
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_rest_goal)
        self.horizontalLayout_11.setObjectName('horizontalLayout_11')
        self.label_22 = QtWidgets.QLabel(self.frame_rest_goal)
        self.label_22.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName('label_22')
        self.horizontalLayout_11.addWidget(self.label_22)
        self.spinbox_minutes_rest = QtWidgets.QSpinBox(self.frame_rest_goal)
        self.spinbox_minutes_rest.setStyleSheet(
            'QSpinBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            '\n'
            'font: 75 11px "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'background-position: right;\n'
            'background-repeat: none;\n'
            'background-origin: content;\n'
            'padding-right: 7px;\n'
            '    color: rgb(172, 172, 174);\n'
            '}\n'
            '\n'
            'QSpinBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '\n'
            '}\n'
            '\n'
            ''
        )
        self.spinbox_minutes_rest.setMaximum(9999)
        self.spinbox_minutes_rest.setObjectName('spinbox_minutes_rest')
        self.horizontalLayout_11.addWidget(self.spinbox_minutes_rest)
        self.label_24 = QtWidgets.QLabel(self.frame_rest_goal)
        self.label_24.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName('label_24')
        self.horizontalLayout_11.addWidget(self.label_24)
        self.spinbox_actions_rest = QtWidgets.QSpinBox(self.frame_rest_goal)
        self.spinbox_actions_rest.setStyleSheet(
            'QSpinBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            '\n'
            'font: 75 11px "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'background-position: right;\n'
            'background-repeat: none;\n'
            'background-origin: content;\n'
            'padding-right: 7px;\n'
            '    color: rgb(172, 172, 174);\n'
            '}\n'
            '\n'
            'QSpinBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '\n'
            '}\n'
            '\n'
            ''
        )
        self.spinbox_actions_rest.setMaximum(9999)
        self.spinbox_actions_rest.setObjectName('spinbox_actions_rest')
        self.horizontalLayout_11.addWidget(self.spinbox_actions_rest)
        self.label_23 = QtWidgets.QLabel(self.frame_rest_goal)
        self.label_23.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            ''
        )
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName('label_23')
        self.horizontalLayout_11.addWidget(self.label_23)
        self.verticalLayout_21.addWidget(
            self.frame_rest_goal, 0, QtCore.Qt.AlignHCenter
        )
        self.label_30 = QtWidgets.QLabel(self.frame_20)
        self.label_30.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName('label_30')
        self.verticalLayout_21.addWidget(self.label_30)
        self.frame_29 = QtWidgets.QFrame(self.frame_20)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName('frame_29')
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_17.setObjectName('horizontalLayout_17')
        self.radiobutton_android_automation = QtWidgets.QRadioButton(
            self.frame_29
        )
        self.radiobutton_android_automation.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            '\n'
            '\n'
            ''
        )
        self.radiobutton_android_automation.setObjectName(
            'radiobutton_android_automation'
        )
        self.horizontalLayout_17.addWidget(self.radiobutton_android_automation)
        self.radiobutton_desktop_automation = QtWidgets.QRadioButton(
            self.frame_29
        )
        self.radiobutton_desktop_automation.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            ''
        )
        self.radiobutton_desktop_automation.setObjectName(
            'radiobutton_desktop_automation'
        )
        self.horizontalLayout_17.addWidget(self.radiobutton_desktop_automation)
        self.verticalLayout_21.addWidget(
            self.frame_29, 0, QtCore.Qt.AlignHCenter
        )
        self.label_32 = QtWidgets.QLabel(self.frame_20)
        self.label_32.setStyleSheet(
            'font: 11px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName('label_32')
        self.verticalLayout_21.addWidget(self.label_32)
        self.frame_36 = QtWidgets.QFrame(self.frame_20)
        self.frame_36.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName('frame_36')
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_18.setObjectName('horizontalLayout_18')
        self.radiobutton_lite_instagram = QtWidgets.QRadioButton(self.frame_36)
        self.radiobutton_lite_instagram.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            '\n'
            '\n'
            ''
        )
        self.radiobutton_lite_instagram.setObjectName(
            'radiobutton_lite_instagram'
        )
        self.horizontalLayout_18.addWidget(self.radiobutton_lite_instagram)
        self.radiobutton_official_instagram = QtWidgets.QRadioButton(
            self.frame_36
        )
        self.radiobutton_official_instagram.setStyleSheet(
            'QRadioButton{\n'
            'font: 11px "Malgun Gothic";\n'
            'color: rgb(172, 172, 174);\n'
            'font-weight: bold;\n'
            '}\n'
            'QRadioButton::indicator:checked{\n'
            '    background-color: rgb(172, 172, 174);\n'
            '    border-radius: 6px;\n'
            '    border: 2px solid rgb(165, 165, 165)\n'
            '}\n'
            ''
        )
        self.radiobutton_official_instagram.setObjectName(
            'radiobutton_official_instagram'
        )
        self.horizontalLayout_18.addWidget(self.radiobutton_official_instagram)
        self.verticalLayout_21.addWidget(
            self.frame_36, 0, QtCore.Qt.AlignHCenter
        )
        self.horizontalLayout_5.addWidget(
            self.frame_20, 0, QtCore.Qt.AlignVCenter
        )
        self.verticalLayout_18.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setStyleSheet('')
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName('frame_16')
        self.button_save_config = QtWidgets.QPushButton(self.frame_16)
        self.button_save_config.setGeometry(QtCore.QRect(240, 10, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_save_config.sizePolicy().hasHeightForWidth()
        )
        self.button_save_config.setSizePolicy(sizePolicy)
        self.button_save_config.setMinimumSize(QtCore.QSize(150, 35))
        self.button_save_config.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.button_save_config.setStyleSheet(
            'QPushButton{\n'
            'background-image: url(:/imagens/imagens/diskette_resized.png);\n'
            'background-position: left;\n'
            'background-repeat: none;\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: right;\n'
            'border: 0px;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_save_config.setObjectName('button_save_config')
        self.verticalLayout_18.addWidget(self.frame_16)
        self.verticalLayout_17.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.widget_page_config)
        self.widget_page_start = QtWidgets.QWidget()
        self.widget_page_start.setObjectName('widget_page_start')
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_page_start)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName('verticalLayout_22')
        self.frame_28 = QtWidgets.QFrame(self.widget_page_start)
        self.frame_28.setStyleSheet('background-color: rgb(50, 50, 62);')
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName('frame_28')
        self.label_25 = QtWidgets.QLabel(self.frame_28)
        self.label_25.setGeometry(QtCore.QRect(100, 9, 401, 31))
        self.label_25.setStyleSheet(
            'font: 14pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName('label_25')
        self.combobox_connected_devices = QtWidgets.QComboBox(self.frame_28)
        self.combobox_connected_devices.setGeometry(
            QtCore.QRect(150, 50, 300, 30)
        )
        self.combobox_connected_devices.setMinimumSize(QtCore.QSize(300, 30))
        self.combobox_connected_devices.setStyleSheet(
            'QComboBox{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(172, 172, 174);\n'
            'font: 75 11px "Myanmar Text";\n'
            'font-weight: bold;\n'
            'padding-left: 5px;\n'
            'padding-right: 7px;\n'
            '}\n'
            '\n'
            'QComboBox:focus{\n'
            'border: 1px outset rgb(70, 70, 82);\n'
            '}\n'
            '\n'
            'QComboBox::drop-down {\n'
            '    background-color: rgb(39, 39, 47);\n'
            '    width: 25px; \n'
            '    border-right: 0px;\n'
            '}\n'
            '\n'
            'QComboBox::down-arrow {\n'
            '    image: url(:/imagens/imagens/dropdown.png);\n'
            '}\n'
            '\n'
            ''
        )
        self.combobox_connected_devices.setObjectName(
            'combobox_connected_devices'
        )
        self.combobox_connected_devices.addItem('')
        self.frame_added_accounts = QtWidgets.QFrame(self.frame_28)
        self.frame_added_accounts.setGeometry(QtCore.QRect(30, 100, 541, 300))
        self.frame_added_accounts.setMinimumSize(QtCore.QSize(541, 300))
        self.frame_added_accounts.setStyleSheet('')
        self.frame_added_accounts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_added_accounts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_added_accounts.setObjectName('frame_added_accounts')
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(
            self.frame_added_accounts
        )
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName('verticalLayout_23')
        self.frame_31 = QtWidgets.QFrame(self.frame_added_accounts)
        self.frame_31.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_31.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName('frame_31')
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName('horizontalLayout_12')
        self.label_26 = QtWidgets.QLabel(self.frame_31)
        self.label_26.setMinimumSize(QtCore.QSize(150, 0))
        self.label_26.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_26.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'border-right: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;\n'
            'border-top-left-radius:5px;'
        )
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName('label_26')
        self.horizontalLayout_12.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.frame_31)
        self.label_27.setMinimumSize(QtCore.QSize(236, 0))
        self.label_27.setMaximumSize(QtCore.QSize(236, 16777215))
        self.label_27.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'border-right: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;'
        )
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName('label_27')
        self.horizontalLayout_12.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.frame_31)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_28.setMaximumSize(QtCore.QSize(173, 16777215))
        self.label_28.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;\n'
            'border-top-right-radius:5px;'
        )
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName('label_28')
        self.horizontalLayout_12.addWidget(self.label_28)
        self.verticalLayout_23.addWidget(self.frame_31)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_added_accounts)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 220))
        self.scrollArea_2.setStyleSheet('border: 0px;')
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName('scrollArea_2')
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(
            QtCore.QRect(0, 0, 541, 270)
        )
        self.scrollAreaWidgetContents_2.setObjectName(
            'scrollAreaWidgetContents_2'
        )
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents_2
        )
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName('verticalLayout_25')
        self.frame_32 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName('frame_32')
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName('verticalLayout_26')
        self.frame_33 = QtWidgets.QFrame(self.frame_32)
        self.frame_33.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_33.setStyleSheet('')
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName('frame_33')
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName('horizontalLayout_16')
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_34.setStyleSheet('')
        self.frame_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName('frame_34')
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_27.setObjectName('verticalLayout_27')
        self.label_29 = QtWidgets.QLabel(self.frame_34)
        self.label_29.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName('label_29')
        self.verticalLayout_27.addWidget(self.label_29)
        self.horizontalLayout_16.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_33)
        self.frame_35.setMinimumSize(QtCore.QSize(236, 0))
        self.frame_35.setMaximumSize(QtCore.QSize(236, 16777215))
        self.frame_35.setStyleSheet('')
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName('frame_35')
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_32.setObjectName('verticalLayout_32')
        self.label_31 = QtWidgets.QLabel(self.frame_35)
        self.label_31.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName('label_31')
        self.verticalLayout_32.addWidget(self.label_31)
        self.horizontalLayout_16.addWidget(self.frame_35)
        self.frame_37 = QtWidgets.QFrame(self.frame_33)
        self.frame_37.setStyleSheet('border: 0px;')
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName('frame_37')
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName('verticalLayout_29')
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_37)
        self.pushButton_8.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_8.setMaximumSize(QtCore.QSize(18, 16777215))
        self.pushButton_8.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.pushButton_8.setStyleSheet(
            'background-image: url(:/imagens/imagens/more_resized.png);'
        )
        self.pushButton_8.setText('')
        self.pushButton_8.setObjectName('pushButton_8')
        self.verticalLayout_29.addWidget(self.pushButton_8)
        self.horizontalLayout_16.addWidget(
            self.frame_37, 0, QtCore.Qt.AlignHCenter
        )
        self.verticalLayout_26.addWidget(self.frame_33)
        self.verticalLayout_25.addWidget(self.frame_32, 0, QtCore.Qt.AlignTop)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_23.addWidget(self.scrollArea_2)
        self.button_start_all = QtWidgets.QPushButton(self.frame_28)
        self.button_start_all.setGeometry(QtCore.QRect(70, 400, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_start_all.sizePolicy().hasHeightForWidth()
        )
        self.button_start_all.setSizePolicy(sizePolicy)
        self.button_start_all.setMinimumSize(QtCore.QSize(150, 35))
        self.button_start_all.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.button_start_all.setStyleSheet(
            'QPushButton{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: center;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_start_all.setObjectName('button_start_all')
        self.button_stop_all = QtWidgets.QPushButton(self.frame_28)
        self.button_stop_all.setGeometry(QtCore.QRect(230, 400, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_stop_all.sizePolicy().hasHeightForWidth()
        )
        self.button_stop_all.setSizePolicy(sizePolicy)
        self.button_stop_all.setMinimumSize(QtCore.QSize(150, 35))
        self.button_stop_all.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.button_stop_all.setStyleSheet(
            'QPushButton{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: center;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_stop_all.setObjectName('button_stop_all')
        self.button_add_profiles = QtWidgets.QPushButton(self.frame_28)
        self.button_add_profiles.setGeometry(QtCore.QRect(390, 400, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_add_profiles.sizePolicy().hasHeightForWidth()
        )
        self.button_add_profiles.setSizePolicy(sizePolicy)
        self.button_add_profiles.setMinimumSize(QtCore.QSize(150, 35))
        self.button_add_profiles.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.button_add_profiles.setStyleSheet(
            'QPushButton{\n'
            'border: 1px solid rgb(70, 70, 82);\n'
            'border-radius: 5px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'padding-right: 10px;\n'
            'font: 11px "Malgun Gothic";\n'
            'font-weight: bold;\n'
            'color: rgb(230, 230, 230);\n'
            'text-align: center;\n'
            '\n'
            '}\n'
            '\n'
            'QPushButton:hover{\n'
            'background-color: rgb(80, 80, 92);\n'
            '}\n'
            '\n'
            ''
        )
        self.button_add_profiles.setObjectName('button_add_profiles')
        self.verticalLayout_22.addWidget(self.frame_28)
        self.stackedWidget.addWidget(self.widget_page_start)
        self.widget_page_devices = QtWidgets.QWidget()
        self.widget_page_devices.setObjectName('widget_page_devices')
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(
            self.widget_page_devices
        )
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName('verticalLayout_16')
        self.content = QtWidgets.QFrame(self.widget_page_devices)
        self.content.setStyleSheet('background-color: rgb(50, 50, 62);')
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName('content')
        self.label = QtWidgets.QLabel(self.content)
        self.label.setGeometry(QtCore.QRect(40, 30, 171, 20))
        self.label.setStyleSheet(
            'font: 18px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label.setObjectName('label')
        self.frame = QtWidgets.QFrame(self.content)
        self.frame.setGeometry(QtCore.QRect(20, 60, 211, 121))
        self.frame.setMaximumSize(QtCore.QSize(211, 121))
        self.frame.setStyleSheet(
            'border: 1px solid rgb(70, 70, 82);\n' 'border-radius: 5px;'
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName('frame')
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName('verticalLayout_6')
        self.textedit_usb_devices = QtWidgets.QPlainTextEdit(self.frame)
        self.textedit_usb_devices.setMaximumSize(QtCore.QSize(211, 121))
        self.textedit_usb_devices.setStyleSheet(
            'border: 0px;\n'
            'padding: 10px;\n'
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);'
        )
        self.textedit_usb_devices.setObjectName('textedit_usb_devices')
        self.verticalLayout_6.addWidget(self.textedit_usb_devices)
        self.button_change_to_wifi = QtWidgets.QPushButton(self.content)
        self.button_change_to_wifi.setGeometry(QtCore.QRect(40, 190, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_change_to_wifi.sizePolicy().hasHeightForWidth()
        )
        self.button_change_to_wifi.setSizePolicy(sizePolicy)
        self.button_change_to_wifi.setMinimumSize(QtCore.QSize(131, 31))
        self.button_change_to_wifi.setStyleSheet(
            'QPushButton{\n'
            'font: 13px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;\n'
            'background-image: url(:/imagens/imagens/refresh_resized.png);\n'
            'background-position: left;\n'
            'background-repeat: none;\n'
            'border: 0px;\n'
            'background-origin: content;\n'
            'padding-left: 8px;\n'
            'border-radius: 5px;\n'
            '}\n'
            'QPushButton:hover{\n'
            'background-color: rgb(69, 69, 77);\n'
            '}\n'
            ''
        )
        self.button_change_to_wifi.setObjectName('button_change_to_wifi')
        self.label_2 = QtWidgets.QLabel(self.content)
        self.label_2.setGeometry(QtCore.QRect(36, 240, 211, 20))
        self.label_2.setStyleSheet(
            'font: 18px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_2.setObjectName('label_2')
        self.frame_2 = QtWidgets.QFrame(self.content)
        self.frame_2.setGeometry(QtCore.QRect(20, 270, 211, 121))
        self.frame_2.setMaximumSize(QtCore.QSize(211, 121))
        self.frame_2.setStyleSheet(
            'border: 1px solid rgb(70, 70, 82);\n' 'border-radius: 5px;'
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName('frame_2')
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName('verticalLayout_5')
        self.textedit_connect_emulators = QtWidgets.QTextEdit(self.frame_2)
        self.textedit_connect_emulators.setStyleSheet(
            'border: 0px;\n'
            'padding: 10px;\n'
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);'
        )
        self.textedit_connect_emulators.setObjectName(
            'textedit_connect_emulators'
        )
        self.verticalLayout_5.addWidget(self.textedit_connect_emulators)
        self.button_connect_emulators = QtWidgets.QPushButton(self.content)
        self.button_connect_emulators.setGeometry(
            QtCore.QRect(40, 400, 171, 31)
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.button_connect_emulators.sizePolicy().hasHeightForWidth()
        )
        self.button_connect_emulators.setSizePolicy(sizePolicy)
        self.button_connect_emulators.setMinimumSize(QtCore.QSize(131, 31))
        self.button_connect_emulators.setStyleSheet(
            'QPushButton{\n'
            'font: 13px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;\n'
            '    background-image: url(:/imagens/imagens/link_resized.png);\n'
            'background-position: left;\n'
            'background-repeat: none;\n'
            'border: 0px;\n'
            'background-origin: content;\n'
            'padding-left:35px;\n'
            'padding-right: 10px;\n'
            'border-radius: 5px;\n'
            '}\n'
            'QPushButton:hover{\n'
            'background-color: rgb(69, 69, 77);\n'
            '}\n'
            ''
        )
        self.button_connect_emulators.setObjectName('button_connect_emulators')
        self.label_3 = QtWidgets.QLabel(self.content)
        self.label_3.setGeometry(QtCore.QRect(310, 50, 231, 31))
        self.label_3.setStyleSheet(
            'font: 18px "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_3.setObjectName('label_3')
        self.frame_17 = QtWidgets.QFrame(self.content)
        self.frame_17.setGeometry(QtCore.QRect(270, 90, 301, 250))
        self.frame_17.setMinimumSize(QtCore.QSize(301, 250))
        self.frame_17.setStyleSheet('')
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName('frame_17')
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName('verticalLayout_13')
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName('frame_18')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.label_4 = QtWidgets.QLabel(self.frame_18)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'border-right: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;\n'
            'border-top-left-radius:5px;'
        )
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName('label_4')
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_18)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'border-right: 1px solid rgb(70, 70, 82);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;'
        )
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName('label_5')
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_18)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setStyleSheet(
            'background-color: rgb(39, 39, 47);\n'
            'color: rgb(255, 255, 255);\n'
            'font-weight: bold;\n'
            'border-top-right-radius:5px;'
        )
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName('label_6')
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout_13.addWidget(self.frame_18)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_17)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 220))
        self.scrollArea.setStyleSheet('border: 0px;')
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName('scrollArea')
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 301, 220))
        self.scrollAreaWidgetContents.setObjectName('scrollAreaWidgetContents')
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents
        )
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName('verticalLayout_7')
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName('frame_3')
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName('verticalLayout_8')
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_4.setStyleSheet('')
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName('frame_4')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet('border: 0px;')
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName('frame_6')
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName('verticalLayout_9')
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName('label_7')
        self.verticalLayout_9.addWidget(self.label_7)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMaximumSize(QtCore.QSize(99, 16777215))
        self.frame_7.setStyleSheet('')
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName('frame_7')
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName('verticalLayout_14')
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setMinimumSize(QtCore.QSize(22, 22))
        self.frame_12.setMaximumSize(QtCore.QSize(22, 20))
        self.frame_12.setStyleSheet(
            'QFrame{\n'
            'background-image: url(:/imagens/imagens/usb_resized.png);\n'
            'background-position:center;\n'
            'background-repeat: none;\n'
            'border-radius: 11px;\n'
            '}\n'
            'QFrame:hover{\n'
            'background-color: rgb(70, 70, 82);\n'
            '}\n'
            ''
        )
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName('frame_12')
        self.verticalLayout_14.addWidget(
            self.frame_12, 0, QtCore.Qt.AlignHCenter
        )
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setStyleSheet('border: 0px;')
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName('frame_8')
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName('verticalLayout_10')
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_6.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_6.setMaximumSize(QtCore.QSize(18, 16777215))
        self.pushButton_6.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.pushButton_6.setStyleSheet(
            'background-image: url(:/imagens/imagens/more_resized.png);'
        )
        self.pushButton_6.setText('')
        self.pushButton_6.setObjectName('pushButton_6')
        self.verticalLayout_10.addWidget(self.pushButton_6)
        self.horizontalLayout_2.addWidget(
            self.frame_8, 0, QtCore.Qt.AlignHCenter
        )
        self.verticalLayout_8.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName('frame_5')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setStyleSheet('border: 0px;')
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName('frame_9')
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName('verticalLayout_11')
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setStyleSheet(
            'font: 8pt "Yu Gothic UI Semilight";\n'
            'color: rgb(230, 230, 230);\n'
            'font-weight:bold;'
        )
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName('label_8')
        self.verticalLayout_11.addWidget(self.label_8)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setMaximumSize(QtCore.QSize(99, 16777215))
        self.frame_10.setStyleSheet('')
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName('frame_10')
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName('verticalLayout_15')
        self.frame_13 = QtWidgets.QFrame(self.frame_10)
        self.frame_13.setMinimumSize(QtCore.QSize(22, 22))
        self.frame_13.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_13.setStyleSheet(
            'QFrame{\n'
            'background-image: url(:/imagens/imagens/wi-fi-resized.png);\n'
            'background-position:center;\n'
            'background-repeat: none;\n'
            'border-radius: 11px;\n'
            '}\n'
            'QFrame:hover{\n'
            'background-color: rgb(70, 70, 82);\n'
            '}\n'
            ''
        )
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName('frame_13')
        self.verticalLayout_15.addWidget(
            self.frame_13, 0, QtCore.Qt.AlignHCenter
        )
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setStyleSheet('border: 0px;')
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName('frame_11')
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName('verticalLayout_12')
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_7.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButton_7.setMaximumSize(QtCore.QSize(18, 16777215))
        self.pushButton_7.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.pushButton_7.setStyleSheet(
            'background-image: url(:/imagens/imagens/more_resized.png);'
        )
        self.pushButton_7.setText('')
        self.pushButton_7.setObjectName('pushButton_7')
        self.verticalLayout_12.addWidget(self.pushButton_7)
        self.horizontalLayout_3.addWidget(
            self.frame_11, 0, QtCore.Qt.AlignHCenter
        )
        self.verticalLayout_8.addWidget(self.frame_5)
        self.verticalLayout_7.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_13.addWidget(self.scrollArea)
        self.verticalLayout_16.addWidget(self.content)
        self.stackedWidget.addWidget(self.widget_page_devices)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.main_frame)
        kwai_bot.setCentralWidget(self.centralwidget)

        self.retranslateUi(kwai_bot)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(kwai_bot)

    def retranslateUi(self, kwai_bot):
        _translate = QtCore.QCoreApplication.translate
        kwai_bot.setWindowTitle(_translate('kwai_bot', 'MainWindow'))
        self.page_devices.setText(_translate('kwai_bot', ' Dispositivos'))
        self.page_start.setText(_translate('kwai_bot', '           Iniciar'))
        self.page_options.setText(_translate('kwai_bot', '    Configurações'))
        self.label_9.setText(
            _translate('kwai_bot', 'Defina o tempo entre ações')
        )
        self.label_10.setText(_translate('kwai_bot', 'Entre'))
        self.label_11.setText(_translate('kwai_bot', 'e'))
        self.label_12.setText(_translate('kwai_bot', 'segundos'))
        self.label_13.setText(
            _translate('kwai_bot', 'Trocar de conta a cada quantas ações?')
        )
        self.label_14.setText(_translate('kwai_bot', 'ações'))
        self.label_15.setText(
            _translate('kwai_bot', 'Trocar de conta ao ficar sem tarefas?')
        )
        self.radiobutton_change_actions.setText(_translate('kwai_bot', 'Sim'))
        self.radiobutton_dont_change_actions.setText(
            _translate('kwai_bot', 'Não')
        )
        self.label_16.setText(
            _translate('kwai_bot', 'Aguardar quantos segundos para trocar?')
        )
        self.label_17.setText(_translate('kwai_bot', 'segundos'))
        self.label_18.setText(
            _translate('kwai_bot', 'Quais tipos de ações realizar?')
        )
        self.checkbox_like.setText(_translate('kwai_bot', 'Curtir'))
        self.checkbox_follow.setText(_translate('kwai_bot', 'Seguir'))
        self.label_19.setText(
            _translate('kwai_bot', 'Deseja usar meta de ações?')
        )
        self.radiobutton_enable_goal.setText(_translate('kwai_bot', 'Sim'))
        self.radiobutton_disable_goal.setText(_translate('kwai_bot', 'Não'))
        self.label_21.setText(_translate('kwai_bot', 'ações'))
        self.label_20.setText(
            _translate('kwai_bot', 'Deseja usar meta de descanso?')
        )
        self.radiobutton_enable_rest_goal.setText(
            _translate('kwai_bot', 'Sim')
        )
        self.radiobutton_disable_rest_goal.setText(
            _translate('kwai_bot', 'Não')
        )
        self.label_22.setText(_translate('kwai_bot', 'Descansar'))
        self.label_24.setText(_translate('kwai_bot', 'min a cada'))
        self.label_23.setText(_translate('kwai_bot', 'ações'))
        self.label_30.setText(
            _translate('kwai_bot', 'Selecione a plataforma de automação')
        )
        self.radiobutton_android_automation.setText(
            _translate('kwai_bot', 'Android')
        )
        self.radiobutton_desktop_automation.setText(
            _translate('kwai_bot', 'Desktop')
        )
        self.label_32.setText(
            _translate('kwai_bot', 'Selecione o APP de automação')
        )
        self.radiobutton_lite_instagram.setText(
            _translate('kwai_bot', 'Instagram Lite')
        )
        self.radiobutton_official_instagram.setText(
            _translate('kwai_bot', 'Instagram Oficial')
        )
        self.button_save_config.setText(
            _translate('kwai_bot', 'Salvar configurações')
        )
        self.label_25.setText(
            _translate('kwai_bot', 'Selecione o dispositivo:')
        )
        self.combobox_connected_devices.setItemText(
            0, _translate('kwai_bot', 'Nenhum dispositivo conectado')
        )
        self.label_26.setText(_translate('kwai_bot', 'Usuário'))
        self.label_27.setText(_translate('kwai_bot', 'Logs'))
        self.label_28.setText(_translate('kwai_bot', 'Ações'))
        self.label_29.setText(_translate('kwai_bot', '@willenrocha1'))
        self.label_31.setText(
            _translate('kwai_bot', 'Ação realizada com sucesso!')
        )
        self.button_start_all.setText(_translate('kwai_bot', 'Iniciar tudo'))
        self.button_stop_all.setText(_translate('kwai_bot', 'Parar tudo'))
        self.button_add_profiles.setText(
            _translate('kwai_bot', 'Adicionar perfis')
        )
        self.label.setText(_translate('kwai_bot', 'Conectar via Wi-Fi:'))
        self.button_change_to_wifi.setText(
            _translate('kwai_bot', 'Mudar para Wi-Fi')
        )
        self.label_2.setText(_translate('kwai_bot', 'Conectar emuladores:'))
        self.textedit_connect_emulators.setPlaceholderText(
            _translate('kwai_bot', '192.168.0.1:5555')
        )
        self.button_connect_emulators.setText(
            _translate('kwai_bot', 'Conectar')
        )
        self.label_3.setText(
            _translate('kwai_bot', 'Dispositivos conectados:')
        )
        self.label_4.setText(_translate('kwai_bot', 'ID'))
        self.label_5.setText(_translate('kwai_bot', 'Conexão'))
        self.label_6.setText(_translate('kwai_bot', 'Ações'))
        self.label_7.setText(_translate('kwai_bot', '#12345'))
        self.label_8.setText(_translate('kwai_bot', '#56789'))
